name: httpfs
dependencies:
  - python>=3.8.0
  - pip
  - pyopenssl
  - pip:
      - fusepy>=3.0.1
      - requests
      - ujson
      - pylint
      - pytest
      - pytest-cov
      - coverage<5
      - pytest-mock
